import { createSelector } from "@reduxjs/toolkit";

const selectState = state => state;
export const getAuthState = createSelector([selectState],
    state => state.auth);
export const getRoleState = createSelector([selectState],
    state => state.role);
export const getCompanyState = createSelector([selectState],
    state => state.company);
export const getBrFrState = createSelector([selectState],
    state => state.brFr);
export const getModuleFeatureMapperState = createSelector([selectState],
    state => state.moduleFeatureMapper);
export const getEmployeeEnrollState = createSelector([selectState],
    state => state.employeeEnroll);
export const getBankState = createSelector([selectState],
    state => state.bank);
export const getModuleState = createSelector([selectState],
    state => state.module);
export const getFloorState = createSelector([selectState],
    state => state.floor);
export const getShiftingTypeState = createSelector([selectState],
    state => state.shiftingType);
export const getUnitTypeState = createSelector([selectState],
    state => state.unitType);
export const getPaymentTypeState = createSelector([selectState],
    state => state.paymentType);
export const getPaymentModeState = createSelector([selectState],
    state => state.paymentMode);
export const getThemeState = createSelector([selectState],
    state => state.theme);
export const getEnquiryState = createSelector([selectState],
    state => state.enquiry);
export const getVehicleCompanyState = createSelector([selectState],
    state => state.vehicleCompany);
export const getVehicleTypeState = createSelector([selectState],
    state => state.vehicleType);
export const getVehicleLoadSizeState = createSelector([selectState],
    state => state.vehicleLoadSize);
export const getVehicleModelState = createSelector([selectState],
    state => state.vehicleModel);
export const getVehicleAccessoriesState = createSelector([selectState],
    state => state.vehicleAccessories);
export const getVehicleColorState = createSelector([selectState],
    state => state.vehicleColor);
export const getVehicleInsuranceCompanyState = createSelector([selectState],
    state => state.vehicleInsuranceCompany);
export const getPlanState = createSelector([selectState],
    state => state.plan);
export const getPurchaseState = createSelector([selectState],
    state => state.purchase);
export const getGovtRegistrationState = createSelector([selectState],
    state => state.govtRegistration);
export const getSerialSettingState = createSelector([selectState],
    state => state.serialSetting);
export const getTemplateState = createSelector([selectState],
    state => state.template);
export const getAssignTemplateState = createSelector([selectState],
    state => state.assignTemplate);
export const getDocumentFooterContentState = createSelector([selectState],
    state => state.documentFooterContent);
export const getQuotationState = createSelector([selectState],
    state => state.quotation);
export const getAccountState = createSelector([selectState],
    state => state.account);
export const getFollowUpsState = createSelector([selectState],
    state => state.followUps);
export const getSetSurveyState = createSelector([selectState],
    state => state.setSurvey);
export const getPackingMaterialState = createSelector([selectState],
    state => state.packingMaterial);
export const getItemListState = createSelector([selectState],
    state => state.itemList);
export const getCompanyContactState = createSelector([selectState],
    state => state.companyContacts);
export const getCompanyDocumentState = createSelector([selectState],
    state => state.companyDocuments);
export const getSignatureState = createSelector([selectState],
    state => state.signature);
export const getDriverState = createSelector([selectState],
    state => state.driver);
export const getVehicleState = createSelector([selectState],
    state => state.vehicle);
export const getUtilState = createSelector([selectState],
    state => state.utils);
export const getLocationState = createSelector([selectState],
    state => state.location);
export const getGenerateTemplateState = createSelector([selectState],
    state => state.generateTemplate);

